services:
  zookeeper:
    image: ubuntu/zookeeper:latest
    ports:
      - "2181:2181"
  kafka:
    image: ubuntu/kafka:latest
    depends_on:
      - zookeeper
    environment:
      - ZOOKEEPER_HOST=zookeeper
      - ZOOKEEPER_PORT=2181
    ports:
      - "9092:9092"
  api:
    depends_on:
      - kafka
    image: metatron-api:localdev
    build: .
    ports:
      - "3000:3000"
    volumes:
      - ./api:/dist/api
    environment:
      - API_SERVER_PORT=3000
    stdin_open: true
    tty: true
    entrypoint: /bin/bash
  piper:
    depends_on:
      - kafka
    image: metatron-piper:localdev
    build: .
    volumes:
      - ./workers/worker_piper:/dist/worker
    stdin_open: true
    tty: true
    entrypoint: /bin/bash
#  llama:
#    image: metatron-llama:localdev
#    build: .
#    ports:
#      - "3001:3001"
#    volumes:
#      - ./api:/dist/api
#    environment:
#      - API_SERVER_PORT=3001
#    stdin_open: true
#    tty: true
#    entrypoint: /bin/bash