FROM piper:latest AS base
RUN rm -rf /build
WORKDIR /dist
RUN rm piper_*.tar.gz

FROM node:lts-slim AS localdev
ENV API_SERVER_PORT=3000
WORKDIR /dist
COPY --from=base /dist .

FROM localdev AS build
COPY api /dist/api
WORKDIR /dist/api
RUN cd /dist/api && npm install --omit=dev
ENTRYPOINT ["npm", "start"]
