x-base-service: &base-service
  stdin_open: true
  tty: true
  entrypoint: /bin/bash

x-metatron-service: &metatron-service
  <<: *base-service
  depends_on:
    - kafka
  build: .

services:
  zookeeper:
    image: ubuntu/zookeeper:latest
    ports:
      - "2181:2181"

  kafka:
    image: ubuntu/kafka:latest
    depends_on:
      - zookeeper
    environment:
      - ZOOKEEPER_HOST=zookeeper
      - ZOOKEEPER_PORT=2181
    ports:
      - "9092:9092"

  api:
    <<: *metatron-service
    image: metatron-api:localdev
    ports:
      - "3000:3000"
    volumes:
      - ./api:/dist/api
    environment:
      - API_SERVER_PORT=3000
  piper:
    <<: *metatron-service
    image: metatron-piper:localdev
    volumes:
      - ./workers/worker_piper:/dist/worker
#  llama:
#    <<: *metatron-service
#    image: metatron-llama:localdev
#    ports:
#      - "3001:3001"
#    volumes:
#      - ./api:/dist/api
#    environment:
#      - API_SERVER_PORT=3001
