FROM piper:latest AS base
RUN rm -rf /build
WORKDIR /dist
RUN curl -L --output voice-en-us-lessac-medium.tar.gz https://github.com/rhasspy/piper/releases/download/v0.0.2/voice-en-us-lessac-medium.tar.gz \
    && tar -xvf voice-en-us-lessac-medium.tar.gz \
    && rm piper_*.tar.gz voice-en-us-lessac-medium.tar.gz

FROM node:lts-slim AS localdev
ENV API_SERVER_PORT=3000
WORKDIR /dist
COPY --from=base /dist .

FROM localdev AS build
COPY workers/worker_piper /dist/worker
WORKDIR /dist/worker
RUN npm install --omit=dev
ENTRYPOINT ["npm", "start"]
